ChallengeAspMVC/Controllers/RecettesController.cs
using AutoMapper;
using ChallengeAspMVC.Models;
using ChallengeAspMVC.Services;
using ChallengeAspMVC.ViewsModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChallengeAspMVC.Controllers
{
    public class RecettesController : Controller
    {
        IIngrediensServices _ingrediensServices;
        IRecettesServices _recettesServicess;

        public RecettesController(IIngrediensServices ingrediensServices, IRecettesServices recettesServicess)
        {
            _ingrediensServices = ingrediensServices;
            _recettesServicess = recettesServicess;
        }
        // GET: Recettes
        public ActionResult Index()
        {
            var Ingredients= _ingrediensServices.ListIngrediens();
            var Recettes = _recettesServicess.ListRecette();
            var RecettesView = Mapper.Map<List<RecettesModels>, List<RecettesViewModels>>(Recettes);
            return View(RecettesView);
        }

        // GET: Recettes/Details/5
        public ActionResult Details(string id)
        {

            var Recette = _recettesServicess.GetRecette(id);
            var RecetteView = Mapper.Map<RecettesModels, RecettesViewModels>(Recette);
            RecetteView.ID = id;
            RecetteView.name = GenerateIdFromTitle(id);
            return View(RecetteView);
        }
        public string GenerateIdFromTitle(string title)
        {
            return title.Replace("-", " ");
        }

        // GET: Recettes/Create
        public ActionResult Create()
        {
            RecettesViewModels rvm= new RecettesViewModels();
            rvm.ingredientsObj = Mapper.Map<List<IngredientModels>, List<IngredientViewModels>>(_ingrediensServices.ListIngrediens());
            return View(rvm);
        }

        // POST: Recettes/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,name,creatorId,isAvailable,calories,preparation")] RecettesViewModels recettesViewModels, string[] ingredientsObj, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                RecettesViewModels rvm = new RecettesViewModels();
                rvm.ingredientsObj = Mapper.Map<List<IngredientModels>, List<IngredientViewModels>>(_ingrediensServices.ListIngrediens());
                return View(rvm);
            }
            // TODO: Add insert logic here
            if (file != null && file.ContentLength > 0)
            {
                // extract only the fielname
                var fileName = Path.GetFileName(file.FileName);
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/img/recettes"), fileName);
                file.SaveAs(path);
                recettesViewModels.picture = "img/recettes/" + fileName;
            }
            else
            {
                recettesViewModels.picture = "img/recettes/tarte-citron-meringue.jpg";
            }

            //check if ingredien betin 4 and 10
            if (ingredientsObj == null || ingredientsObj.Length > 10 || ingredientsObj.Length < 4)
            {
                return Json("{'KO'}");
            }

            //Add User to the Recette 

            recettesViewModels.userAspId = User.Identity.GetUserId();

            var recettesModels = new RecettesModels();
            recettesModels = Mapper.Map<RecettesViewModels, RecettesModels>(recettesViewModels);
            var Ingredientsdb = _ingrediensServices.ListIngrediens();
            var ss = (from u in Ingredientsdb
                      where ingredientsObj.Contains(u.IngredientId)
                       select u);
            var Ingredients = _ingrediensServices.ListIngrediens().Where(a => ingredientsObj.Any(x => x == a.IngredientId)).ToList();
            //Add Ingredient to Recette
            recettesModels.ingredientsObj = Ingredients;
            //generate Recette ID from the Recette Name
            var id = recettesViewModels.name.ToLower().Replace(" ","-");
            recettesModels.ID = id;
                
            var ssss = recettesViewModels.name;

            _recettesServicess.AddRecette(recettesModels);
            return RedirectToAction("Index");
              

        }

        // GET: Recettes/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Recettes/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recettes/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Recettes/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ChallengeAspMVC/Views/Recettes/Create.cshtml
@model ChallengeAspMVC.ViewsModels.RecettesViewModels

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm("Create", "Recettes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="col-xs-12 col-sm-9">
        <div class="content" id="content_recettes_new">

            <h1 class="page-title">Nouvelle recette</h1>
            @Html.ValidationSummary()
            <section class="section">
                <div class="row">
                    <div class="col-xs-6">
                        <p class="line">
                            <label for="">Nom de la recette</label>
                            <input type="text" name="name"class="mb0 wide" required>
                            @Html.ValidationMessage("name", "Le nom n'est pas assez long")
                        </p>
                        <p class="line">
                            <label for="">Catégorie</label>
                            <select name="" id="" class="mb0 wide">
                                <option value=""></option>
                                <option value="entree">Entrée</option>
                                <option value="plat-principal">Plat principal</option>
                                <option value="dessert">Dessert</option>
                                <option value="boisson">Boisson</option>
                                <option value="aperitif">Apéritif</option>
                                <option value="encas">Encas</option>
                                <option value="dejeuner">Déjeuner / Brunch</option>
                            </select>
                        </p>
                        <p class="line">
                            <label for="">Préparation de votre recette</label>
                            @Html.ValidationMessage("preparation", "Le description est tros courte")
                            <textarea id="recette_desc" name="preparation" class="resizable mb0 wide" required></textarea>
                        </p>
                    </div>
                    <div class="col-xs-6">
                        <p class="line">
                            <label for="">Photo de la recette</label>
                            <input type="file" name="file" class="mb0">
                        </p>
                        <p class="line ac">
                            <img class="current_img" src="img/recette_placeholder.jpg" alt="Visuel recette">
                        </p>
                    </div>
                    <div class="col-xs-12">
                        <div class="hr mt2 mb2"></div>
                    </div>
                    <div class="col-xs-12">
                        <p class="line ac">
                            <label for="">Sélectionnez tous les ingrédients de votre recette</label>
                        </p>
                        <p class="ac">
                            <select name="" id="">
                                <option value="all">Toutes les catégories</option>
                                <option value="viandes">Viandes</option>
                                <option value="legumes">legumes</option>
                                <option value="fruits">fruits</option>
                                <option value="poissons">poissons</option>
                                <option value="produits-laitiers">Produits laitiers</option>
                                <option value="etc">etc...</option>
                            </select>
                            <span class="span-label"><span class="glyphicon glyphicon-menu-right nm"></span></span>
                            <select name="" id="selectIngredien">
                                @foreach (var ingredient in Model.ingredientsObj)
                                {
                                    <option url-picture="@ingredient.picture" value="@ingredient.name">@ingredient.name</option>
                                }
                            </select>
                            <button type="button" onclick="addIngredient()" class="btn btn_color3"><span class="glyphicon glyphicon-plus"></span></button>
                        </p>
                        <div class="ingredients_list">
                            <ul class="list ac" id="ListIng">
                                
                            </ul>
                        </div>
                        <div class="ac">
                            <p class="recette_total_calories">
                                <span class="tit">Valeur calorique <span class="mass">(100g)</span> : </span><span class="val">270<span class="unit">kcal</span></span>
                            </p>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="hr mb2"></div>
                    </div>
                    <div class="col-xs-12 ac">
                        <button type="submit" class="btn btn_color3 recette_save"><span class="glyphicon glyphicon-ok mr0"></span><span>Valider ma recette</span></button>
                    </div>

                    <!-- Afficher au clic sur "valider ma recette" lorsque tout s'est bien déroulé -->
                    <div class="col-xs-12">
                        <p class="ac mt2 tb">
                            <span class="glyphicon glyphicon-thumbs-up color3"></span>
                            <span>Votre recette a bien été ajoutée !</span>
                        </p>
                        <p class="ac">
                            <a class="btn btn_color1" href="communaute_details.html"><span class="glyphicon glyphicon-cutlery"></span><span>Mes recettes</span></a>
                        </p>
                    </div>

                    <!-- Afficher au clic sur "valider ma recette" si certains éléments sont manquants -->
                    <div class="col-xs-12">
                        <p class="ac mt2 tb">
                            <span class="glyphicon glyphicon-exclamation-sign color2"></span>
                            <span>Woops ! Votre recette est super foireuse</span>
                        </p>
                        <p class="ac">Vous avez dû oublier quelque chose...</p>
                    </div>
                </div>
            </section>
        </div>
    </div>
    
}
<script>
    function addIngredient(){
        $("#ListIng").append('<li class="item" id="ingredientAdded'+$("#selectIngredien").val()+'"><img class="item-img" src="/img/ingredients/' + $("#selectIngredien option:selected").attr("url-picture") + '" alt="' + $("#selectIngredien").val() + '"><p class="item-name" title="' + $("#selectIngredien").val() + '">' + $("#selectIngredien").val() + '</p><input type="hidden" name="ingredientsObj" value="' + $("#selectIngredien").val() + '"><button type="button" onclick="removeIngredient(\''+$("#selectIngredien").val()+'\')" class="remove_ingredient"><span class="glyphicon glyphicon-remove"></span></button> </li>');
    }
    function removeIngredient(element) {
        $("#ingredientAdded" + element).remove();
    }
</script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ChallengeAspMVC/Views/Recettes/Delete.cshtml
@model ChallengeAspMVC.Models.RecettesModels

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RecettesModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.USerAsp.picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USerAsp.picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.calories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.calories)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IngredientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IngredientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.preparation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preparation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChallengeAspMVC/Views/Recettes/Details.cshtml
@model ChallengeAspMVC.ViewsModels.RecettesViewModels

@{
    ViewBag.Title = "Details";
}

<div class="col-xs-12 col-sm-9">
    <div class="content" id="content_recettes_details">

        <section class="section">
            <div class="row">
                <div class="col-xs-4">
                    <img class="recette_img" src="/@Model.picture" alt="@Model.name">
                </div>
                <div class="col-xs-8">
                    <h1 class="rec_name">@Model.name</h1>
                    <p class="rec_note">
                        <span class="stars">
                            <span class="star glyphicon glyphicon-heart"></span>
                            <span class="star glyphicon glyphicon-heart"></span>
                            <span class="star glyphicon glyphicon-heart"></span>
                            <span class="star glyphicon glyphicon-heart"></span>
                            <span class="star glyphicon glyphicon-heart"></span>
                        </span>
                        <span class="notes">| 4,8/5 - 120 votes</span>
                    </p>
                    <div class="ingredients_list">
                        <p class="list-title">Ingrédients</p>
                        <ul class="list">
                            @foreach (var ingredient in Model.ingredientsObj)
                            {
                                <li class="item">
                                    <img class="item-img" src="~/img/ingredients/@ingredient.picture" alt="@ingredient.name">
                                    <p class="item-name" title="@ingredient.name">@ingredient.name</p>
                                </li>
                            }
                        </ul>
                    </div>
                    <p class="rec_cat">Catégorie : <span class="val">Plat principal</span></p>
                    <p class="rec_cal">Valeur calorique <span class="for">(100g)</span> : <span class="val">270 kcal</span></p>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="overline-title"><span class="text">Préparation</span></h2>
                </div>
                <div class="col-xs-12">
                    <p>@Model.preparation</p>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="overline-title"><span class="text">Commentaires</span></h2>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="panel">
                        <div class="filters">
                            <h3 class="panel_title">Donnez-nous votre avis !</h3>
                            <form action="/Comments/Create" method="post">
                                @Html.AntiForgeryToken()
                                <input name="RecetteID" value="@Model.ID" type="hidden"/>
                                <input name="userAspId" value="@Model.userAspId" type="hidden" />
                                <div class="filter">
                                    <p><label for="">Notez cette recette</label></p>
                                    <p>
                                        <select name="mark" id="">
                                            <option value="5">5</option>
                                            <option value="4">4</option>
                                            <option value="3">3</option>
                                            <option value="2">2</option>
                                            <option value="1">1</option>
                                        </select>
                                    </p>
                                </div>
                                <div class="filter">
                                    <p><label for="">Le titre de votre commentaire</label></p>
                                    <p><input type="text" name="title" placeholder="ex: Amazingue !" required></p>
                                </div>
                                <div class="filter">
                                    <p><label for="comment">Votre commentaire</label></p>
                                    <textarea name="comment" id="comment" class="wide" placeholder="ex: Franchement cette NgRecette, c’est de la bombe. Le genre de saveurs qui t’éveillent les papilles, t’as vu ! Woula, j’ai kiffé" required></textarea>
                                </div>
                                <div class="ar">
                                    <input type="submit" class="btn btn_color1" value="Poster !">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <ul class="comments">

                        @foreach (var comment in Model.comments)
                        {
                            <li class="comment">
                                <p class="name">@comment.title<span class="note">@comment.mark/5</span></p>
                                <p class="by">par <a href="communaute_details.html">@comment.id</a></p>
                                <p class="text">@comment.comment</p>
                            </li>
                         }

                        <li class="comment">
                            <p class="name">Miam miam miaouuu<span class="note">4/5</span></p>
                            <p class="by">par <a href="communaute_details.html">Béné du 34</a></p>
                            <p class="text">Franchement cette NgRecette, c’est de la bombe. Le genre de saveurs qui t’éveillent les papilles, t’as vu ! Woula, j’ai kiffé</p>
                        </li>
                        <li class="comment">
                            <p class="name">Ca pique !<span class="note">2/5</span></p>
                            <p class="by">par <a href="communaute_details.html">Ades Vapor</a></p>
                            <p class="text">Quelqu'un a mis du piment dans ma sauce, j'ai passé mon dimanche au toilettes. Sinon, tout va bien..</p>
                        </li>
                    </ul>
                    <div class="row showmore">
                        <div class="col-xs-12">
                            <button type="button" class="btn btn_grey"><span class="glyphicon glyphicon-chevron-down"></span>Afficher d'avantage</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="section">
            <h2 class="title">~ Vous aimerez aussi... ~</h2>
            <div class="recettes row">
                <div class="col-xs-6 col-sm-3 recette">
                    <a href="recettes_details.html">
                        <img src="img/recettes/tajine-de-poulet.jpg" alt="Le tajine de ta maman">
                        <div class="top" title="note : 2,4/5">
                            <span class="note">
                                <span class="glyphicon glyphicon-heart"></span>
                                <span class="glyphicon glyphicon-heart"></span>
                            </span>
                        </div>
                        <div class="bot">
                            <p class="name">Tajine de poulet</p>
                        </div>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-3 recette">
                    <a href="recettes_details.html">
                        <img src="img/recettes/tajine-de-poulet.jpg" alt="Le tajine de ta maman">
                        <div class="top" title="note : 2,4/5">
                            <span class="note">
                                <span class="glyphicon glyphicon-heart"></span>
                                <span class="glyphicon glyphicon-heart"></span>
                            </span>
                        </div>
                        <div class="bot">
                            <p class="name">Tajine de poulet</p>
                        </div>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-3 recette">
                    <a href="recettes_details.html">
                        <img src="img/recettes/tajine-de-poulet.jpg" alt="Le tajine de ta maman">
                        <div class="top" title="note : 2,4/5">
                            <span class="note">
                                <span class="glyphicon glyphicon-heart"></span>
                                <span class="glyphicon glyphicon-heart"></span>
                            </span>
                        </div>
                        <div class="bot">
                            <p class="name">Tajine de poulet</p>
                        </div>
                    </a>
                </div>
                <div class="col-xs-6 col-sm-3 recette">
                    <a href="recettes_details.html">
                        <img src="img/recettes/tajine-de-poulet.jpg" alt="Le tajine de ta maman">
                        <div class="top" title="note : 2,4/5">
                            <span class="note">
                                <span class="glyphicon glyphicon-heart"></span>
                                <span class="glyphicon glyphicon-heart"></span>
                            </span>
                        </div>
                        <div class="bot">
                            <p class="name">Tajine de poulet</p>
                        </div>
                    </a>
                </div>
            </div>
        </section>

    </div>
</div>

ChallengeAspMVC/Views/Recettes/Edit.cshtml
@model ChallengeAspMVC.Models.RecettesModels

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RecettesModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userAspId, "userAspId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userAspId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userAspId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isAvailable)
                    @Html.ValidationMessageFor(model => model.isAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.calories, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IngredientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IngredientId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IngredientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preparation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preparation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.preparation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}